typography_spectrum: 0.8043356293346733
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9919731197878718
  lightness: 0.2351542643737048
  saturation: 0.08507629344239831
  rhythmicContrast: 0.8362191917840391
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2876219351310283
analytics:
  google: null
  facebook: null
  twitter: null
name: two trees ministry
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: two trees ministry
description: '"[The one] who eats My flesh and drinks My blood has eternal life"'
purpose: []
